name: Manually Triggered Tagging

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true
        default: 'v1.0.0'
      tag_message:
        description: 'Tag Message'
        required: true
        default: 'Release v1.0.0'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set git user
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"

    - name: Create tag
      run: |
        git tag -a ${{ github.event.inputs.tag_name }} -m "${{ github.event.inputs.tag_message }}"
        git push origin ${{ github.event.inputs.tag_name }}
